version: '3.7'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    deploy:
      replicas: 1
    ports:
      - "9101:80"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.0.1.10'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data: