global:
  scrape_interval: 15s
rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['localhost:9091']

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.0.1.10:9100', '10.0.1.11:9100', '10.0.1.12:9100']

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://10.0.1.10:9106
          - http://10.0.1.11:9106
          - http://10.0.1.12:9106
          - http://10.0.1.11:9091
          - http://10.0.1.11:8100
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.0.1.10:9102
      - target_label: __address__
        replacement: 10.0.1.11:9102
      - target_label: __address__
        replacement: 10.0.1.12:9102

  - job_name: 'Docker swarm'
    static_configs:
      - targets: ['10.0.1.10:9105', '10.0.1.11:9105', '10.0.1.12:9105']
